# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    my_user_provider.class: AppBundle\Security\Core\User\FOSUBUserProvider
services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
    fos_user.doctrine_registry:
        alias: doctrine
    app.upload_listener:
        class: AppBundle\EventListener\UploadListener
        argument: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
