<?php

namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;


class UserPostType extends AbstractType
{
    protected $options;

    public function __construct(array $options = array())
    {
        $this->options = $options;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('title', TextType::class)
            ->add('short_text', TextType::class)
            ->add('text', TextType::class)
            ->add('save', SubmitType::class, array('label' => 'Create Task'));
    }

    public function getName()
    {
        return 'user_post';
    }

    public function configureOptions(OptionsResolver  $resolver)
    {
        $resolver->setDefaults(array(
                'data_class' => 'AppBundle\Entity\UserPost'
            )
        );
    }
}